### ISSUE TITLE
middleware to set headers?

### ISSUE THREAD

**Issue by davehorner** [casualjim/rs-treemux#146]
I am trying to add cors headers to all the routes I've already defined.
I see in the README that you are doing such a thing in the options.
```
async fn global_options(_: Request<Body>) -> Result<Response<Body>, Error> {
  Ok(Response::builder()
      .header("Access-Control-Allow-Methods", "Allow")
      .header("Access-Control-Allow-Origin", "*")
      .body(Body::empty())
      .unwrap())
}
```
How would one do a middleware that adds origin * to all responses using treemux?

**Comment by casualjim** [comment]
I created an example here: https://github.com/casualjim/rs-treemux/blob/main/examples/cors.rs

```shellsession
$ curl -i localhost:3000
HTTP/1.1 200 OK
access-control-allow-origin: *
content-length: 13
date: Tue, 12 Sep 2023 03:51:48 GMT

Hello, World!
```

**Comment by davehorner** [comment]
Funny you should mention the [tower_http](https://docs.rs/tower-http/latest/tower_http/index.html)::[cors](https://docs.rs/tower-http/latest/tower_http/cors/index.html#), I believe that was the first thing ChatGPT suggested to me but I didn't want to take on the dep for a * in the header.  I spent quite some time implementing various  attempts with GPT...I gave in and asked a human.

instead of using the cors package I ended up taking on
+tower = "0.4.13"
+tower-service = "0.3.2"
+tower-layer = "0.3.2"
attempting my own mess.

Thanks so much your example.  No additional deps, exactly what I was looking for and thought possible!

> How did you decide to use this one?
Are you talking about treemux?
I have been using it for some time.

I've been wondering about how to go about packaging a handler or maybe even the router for use as a library.  a https://github.com/rksm/hot-lib-reloader-rs type deal or using a handler written for treemux in https://github.com/cargo-lambda/cargo-lambda.  or embedded in a tauri app.  or exposed via neon to node.

I'm not sure what caused me to pick this up long ago (staticfiles was what brought me).  lol  thank you for sharing.
