### ISSUE TITLE
cargo build reported this error, error[E0432]: unresolved import `tracing`.

### ISSUE THREAD

**Issue by Ilqjx** [casualjim/rs-treemux#17]
![image](https://user-images.githubusercontent.com/53934234/133884453-cacc4ccd-48fb-41c8-b294-05852ca51045.png)

**Comment by Ilqjx** [comment]
I changed it to this, and it can run normally.
![image](https://user-images.githubusercontent.com/53934234/133885529-f7639153-b26c-484e-8aa7-2c61f36d803f.png)
![image](https://user-images.githubusercontent.com/53934234/133885537-b17c2d63-0bb9-41ad-b3ac-fa9203494d4a.png)

**Comment by casualjim** [comment]
Hi sorry about that. I'll add push a new version which avoids the import

**Comment by casualjim** [comment]
Version 0.7.1 works without tracing present

**Comment by Ilqjx** [comment]
Thanks
