### ISSUE TITLE
Leaf_handler may happen covering, is this intentional?

### ISSUE THREAD

**Issue by Ilqjx** [casualjim/rs-treemux#21]
![image](https://user-images.githubusercontent.com/53934234/134793940-17015f04-6bc1-4fff-b894-f9a941fd721f.png)

**Comment by casualjim** [comment]
I'm terribly sorry but I don't know what you mean by covering

**Comment by Ilqjx** [comment]
Yes. There is already a HEAD, it will be replaced.

**Comment by Ilqjx** [comment]
Yes. There is already a HEAD, it will be replaced.

**Comment by casualjim** [comment]
Yes that's intentional.  We register an implicit head handler for every get request.

https://github.com/casualjim/rs-treemux/blob/main/src/tree.rs#L714-L717

**Comment by Ilqjx** [comment]
Thank you so much for answering my question.
