### ISSUE TITLE
difference with actix

### ISSUE THREAD

**Issue by GlenDC** [casualjim/rs-treemux#75]
Dunno if out scope for the documentation for `rs-treemux` but would it be possible to describe the difference with something like actix? I consider Rocket another beast as it is quite big, but from my experience actix is pretty minimal as well and I feel it adds pretty much the same feature set?

Thanks for maintaining this library by the way!

**Comment by GlenDC** [comment]
Hmm given the low acticivity in actix these days that makes me wonder if I should start using axum instead of actix, now that my project is still in the early enough stages... I wonder what the advantages over actix are at this point. Even though it was always claimed to be the fast one.

**Comment by casualjim** [comment]
I built treemux because I wanted something that worked with the `tower::Service` as middleware. In theory (I haven't tried this yet) it should be possible to use any middleware that implements that trait with this library.   Next time I do something in rust I'm giving axum a go

**Comment by GlenDC** [comment]
Yeah I think I'm going to branch my project at the current state and see how it would be with Axum, looks pretty promising and it gives me hope for the future as I was afraid with my choice of actix for the long term maintenance of it all. I'm going to close this issue, as my request is kinda pointless for a toy project.

Nice talking to you again by the way, been a long time.
Hope that one day we might cross path professionally in one capacity or another ;)

**Comment by casualjim** [comment]
we might, feel free to drop by on the go-swagger slack. I'm starting a project around futarchy with the City of Antwerp.
